### ISSUE TITLE
This looks promising, but I have a question.

### ISSUE THREAD

**Issue by vindhaus** [storefront-community/self-order-kiosk#31]
Is there a way yet to integrate this into something like Floreant POS?

**Comment by marxjmoura** [comment]
@vindhaus thanks for your interest in the Storefront Community.

Short answer yes.

The Self-Order Kiosk is essentially a web app. It can be installed on any device or run through a web browser. However, some adaptations may be required depending on the desired solution (e.g. connecting the app to credit card readers).

**Comment by marxjmoura** [comment]
Issue closed due to not receiving feedback from questioner. So I understand that the answer was well understood.
